### ISSUE TITLE
esp32c6啥时候能实现thread br啊？ (TZ-44)

### ISSUE THREAD

**Issue by tomyqg** [espressif/esp-thread-br#1]

**Comment by chshu** [comment]
The Thread BR support on ESP32-C6 will be ready in the coming 1~2 weeks.

Since there is only one antenna on C6, the single chip Thread BR solution has some limitation on performance, we still recommend the two chips solutions (https://github.com/espressif/esp-thread-br#esp-thread-border-router-board), with better performance.

**Comment by tomyqg** [comment]
单从带宽来比较esp-thread和esp-mdf，在节点数量、payload相同的情况下，那个带宽大点（esp mdf目前测试下来不太理想），esp thread 表现如何?

**Comment by chshu** [comment]
Thread 网络的带宽并没有优势，因为 802.15.4 PHY 层的带宽只有 250 Kbps，远低于 Wi-Fi。Thread 网络主要特点是 Mesh，IPv6-based，Low Power。
